site_name: SystemCore 1156 Blog

site_description: Blog do Alpha Testing do SystemCore
site_url: http://1156undercontrol.github.io/

nav:
  - Página principal: index.md
  - Blog: 
    - Blog: blog/index.md
  - Sobre: about/index.md
  

theme:
  logo: assets/Logo.png
  favicon: assets/Logo.png
  language: pt-BR
  name: material
  palette:
    - scheme: default
      primary: dark-blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - toc.follow

extra:
  consent:
    title: Cookie consent
    description: >- 
      Nós usamos cookies para reconhecer suas visitas repetidas e preferências, 
      bem como para medir a eficácia da nossa documentação e verificar se os usuários 
      encontram o que estão buscando. Com o seu consentimento, você nos ajuda a melhorar 
      nossa documentação.
  analytics:
    provider: google
    property: G-Q39SSS6SNG
  extra_css:
    - styles/extra.css
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/1156UnderControl
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/undercontrol1156/
  generator: false
plugins:
  - search
  - blog:
      archive: false


copyright: Copyright &copy; 2025 UnderControl