site_name: SystemCore 1156 Blog

site_description: Blog do Alpha Testing do SystemCore
site_url: http://www.test.com

nav:
  - Página principal: index.md
  - Blog: 
    - Blog: blog/index.md
  - Sobre: about/index.md
  

theme:
  logo: https://avatars.githubusercontent.com/u/24967810?s=96&v=4
  language: pt-BR
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo

plugins:
  - search
  - blog