authors:
  under:
    name: Under Control
    description: Time 1156
    avatar: assets/Logo.png
  carvalho:
    name: Luca Carvalho
    description: Lider da área de programação do 1156
    avatar: https://github.com/carvalhojeo.png
  toso:
    name: Bruno Toso
    description: Diretor de engenharia da stemOS e Mentor do 1156
    avatar: https://github.com/brunoUC.png