name: Grammar Check (PT-BR)

on: [pull_request]

jobs:
  grammar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run LanguageTool via reviewdog
        uses: reviewdog/action-languagetool@v1.22.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          language: pt-BR
          patterns: '**/*.md **/*.txt **/*.rst'
          reporter: github-pr-review
          level: warning
